version: "3.8"
services:
  web:
    image: reacttechtest_web
    container_name: reacttechtest_web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 34000:34000
    volumes:
      - ./src:/app/src/
      - ./package.json:/app/package.json
      - ./tsconfig.json:/app/tsconfig.json
    env_file:
      - .env
    networks:
      - reacttechtest

networks:
  reacttechtest:

volumes:
  reacttechtest:
